apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Replace these with your actual values before applying!
  DATABASE_URL: "postgresql://postgres:P@ssword202e@db.mqbffqueueqqklvuxqdz.supabase.co:5432/postgres" 
  SUPABASE_URL: "https://mqbffqueueqqklvuxqdz.supabase.co"
  SUPABASE_ANON_KEY: "sb_publishable_gxv0LYakK7jt8uNeDua6bg_1HE_ZMY7"
  GEMINI_API_KEY: "AIzaSyCjiCH7KD5ZioFiFgtIuXMhLlCOlz2b_BU"
